all:
  stylesheets: [/opPluginChannelServerPlugin/css/channel]

homeSuccess:
  layout: layoutA

releaseSuccess:
  layout: layoutB

memberListSuccess:
  layout: layoutB

releaseListSuccess:
  layout: layoutB

addReleaseSuccess:
  layout: layoutB
